site_name: itslive
site_description: Client library for NASA Earthdata APIs
site_url: https://nasa-jpl.github.io/itslive-py

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_name: nasa-jpl/itslive-py
repo_url: https://github.com/nasa-jpl/itslive-py
edit_uri: ''

extra_css:
  - css/styles.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: no
            merge_init_into_class: yes
            show_submodules: no
          rendering:
            show_root_heading: false
            show_source: false

nav:
  - OVERVIEW: 'index.md'
  - QUICKSTART: 'quickstart.md'
  - HOW-TO:
      - 'Extract time series from a cube': 'quickstart.md'
      - 'Search and export granules': 'index.md'

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.details
  - meta
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - docs
  - notebooks
  - itslive
